### ISSUE TITLE
Multiple args aren't memoized properly

### ISSUE THREAD

**Issue by cowboy** [addyosmani/memoize.js#1]
This is broken:

``` javascript
function test(a, b) {
  return a * 10 + b;
}

test(11, 1); // 111
test(1, 11); // 21

var memo = memoize(test);
memo(11, 1); // 111
memo(1, 11); // 111
```

Suggestion: build an array of args-to-be-memoized and then use `JSON.stringify` to convert that into a cache key. It's still not perfect, but it will reduce the number of edge cases.

**Comment by addyosmani** [comment]
Closing as fixed with https://github.com/JamieMason/memoize.js/commit/f8b25f84fb53370b3c87767cae8a5b9c5be4fc66
