### ISSUE TITLE
Put it on NPM

### ISSUE THREAD

**Issue by alessioalex** [addyosmani/memoize.js#11]
I would really like to have this module in Node. Thanks!

**Comment by JamieMason** [comment]
Sure, if @addyosmani is happy to do this I don't mind putting it together.

Thanks @alessioalex.

**Comment by alessioalex** [comment]
@JamieMason the fact is that I couldn't find a decent implementation of a `memoization` package. They either use different backend storages or momoize functions no matter of the arguments.

**Comment by addyosmani** [comment]
I'd be happy to merge in whatever is needed to make that happen :)

**Comment by alessioalex** [comment]
@addyosmani sure, I will submit a pull request in no time

**Comment by alessioalex** [comment]
@addyosmani Made the pull request, but you will have to release it under 'memoizejs' because 'memoize' or 'memoize.js' are taken.
