### ISSUE TITLE
IE8: "TypeError: 'JSON' is undefined"

### ISSUE THREAD

**Issue by JamieMason** [addyosmani/memoize.js#6]
Memoize currently has a dependency on JSON.stringify

**Comment by JamieMason** [comment]
These browsers will also be affected: http://caniuse.com/json

**Comment by addyosmani** [comment]
I'll have a look around for compact JSON.stringify implementations (or alternatives) which aren't dependant on the entire JSON/JSON2 libraries. At least before we consider writing something to account for this behaviour. 

Initially reviewing http://www.thomasfrank.se/json_stringify_revisited.html
